// Autogenerated from Pigeon (v0.1.21), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTReply;
@class FLTRequest;
@class FLTPerson;

@interface FLTReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@property(nonatomic, strong, nullable) NSArray * list;
@end

@interface FLTRequest : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@interface FLTPerson : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * age;
@end

@protocol FLTExampleApi
-(void)searchVoid:(FlutterError *_Nullable )error;
-(NSString *)searchArgEmpty:(FlutterError *_Nullable )error;
-(void)searchReturnEmpty:(FlutterError *_Nullable )error;
-(FLTReply *)search:(FLTRequest *)request error:(FlutterError *_Nullable)error;
-(BOOL)searchMore:(int)code person:(FLTPerson *)person error:(FlutterError *_Nullable)error;
-(void)searchMoreAsync:(NSString *)name needFullName:(BOOL)needFullName completion:(void(^)(NSString * _Nullable, FlutterError *_Nullable))completion;
-(void)searchReturnAsync:(int)code person:(FLTPerson *)person completion:(void(^)(FlutterError *_Nullable))completion;
-(void)searchEmptyAsync:(void(^)(FLTReply * _Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTExampleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTExampleApi> _Nullable api);

NS_ASSUME_NONNULL_END
