// Autogenerated from Pigeon (v0.1.21), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSearchReply;
@class FLTSearchRequest;
@class FLTPerson;

@interface FLTSearchReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@property(nonatomic, strong, nullable) NSArray * list;
@end

@interface FLTSearchRequest : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@interface FLTPerson : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * age;
@end

@protocol FLTSearchApi
-(nullable FLTSearchReply *)search:(FLTnull*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable FLTNSNumber numberWithBool: *)searchByCode:(FLTnull*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)searchByName:(nullable FLTnull *)input completion:(void(^)(FLTNSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTSearchApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTSearchApi> _Nullable api);

NS_ASSUME_NONNULL_END
