// Autogenerated from Pigeon (v0.1.21), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSearchReply;
@class FLTSearchRequest;
@class FLTPerson;

@interface FLTSearchReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@property(nonatomic, strong, nullable) NSArray * list;
@end

@interface FLTSearchRequest : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@interface FLTPerson : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * age;
@end

@protocol FLTSearchApi
-(_Nonnull FLTSearchReply *)search:(_Nonnull FLTSearchRequest *)request person:(_Nonnull FLTPerson *)person code:( int)code error:(FlutterError *_Nullable)error;
-(BOOL)searchByCode:( int)code person:(_Nonnull FLTPerson *)person error:(FlutterError *_Nullable)error;
-(void)searchByName:(_Nonnull NSString *)name needFullName:( BOOL)needFullName completion:(void(^)(_Nonnull NSString * _Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTSearchApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTSearchApi> _Nullable api);

NS_ASSUME_NONNULL_END
